# Generated by Django 5.0.6 on 2024-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='kkhaddejah', max_length=100),
            preserve_default=False,
        ),
    ]
